
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { addCartContext } from './context'
import { AddCartProvider } from './addCartProvider'
const inter = Inter({ subsets: ['latin'] })
 




export const metadata = {
  title: 'E-Bharat',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Header/>
        <AddCartProvider> {children}</AddCartProvider>
       
        <Footer/>
        </body>
    </html>
  )
}
